# Generated by Django 5.0.1 on 2024-02-21 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='image',
            field=models.ImageField(default='profiles/default_profile.webp', upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='users.profil'),
        ),
    ]
