# Generated by Django 5.0.3 on 2024-03-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='image',
            field=models.ImageField(default='media/default_profile.webp', upload_to='profiles'),
        ),
    ]
