# Generated by Django 5.0.3 on 2024-03-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='image',
            field=models.ImageField(default='media/default_profile.jpg', upload_to='profiles'),
        ),
    ]
